/**
 * Report Engine — PDF renderer.
 *
 * Converts the HTML renderer's output into a print-ready PDF via Puppeteer.
 * Renderers only transform presentation — the HTML content itself (and all
 * underlying data) comes entirely from HtmlRenderer / BuiltReport.
 */

import puppeteer from "puppeteer";
import type { Renderer } from "../renderer";
import type { BuiltReport } from "../builder";
import { HtmlRenderer, escapeHtml } from "./html";

export const PdfRenderer: Renderer = {
  format: "pdf",

  async render(report: BuiltReport): Promise<Buffer> {
    const html = HtmlRenderer.render(report) as string;
    const reportTitle = escapeHtml(`${report.template.name} — ${report.period}`);

    const browser = await puppeteer.launch({
      headless: true,
      args: ["--no-sandbox", "--disable-setuid-sandbox"],
    });

    try {
      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: "load" });

      const pdfBuffer = await page.pdf({
        format: "A4",
        printBackground: true,
        margin: { top: "20mm", bottom: "20mm", left: "15mm", right: "15mm" },
        displayHeaderFooter: true,
        headerTemplate: `<div style="font-size:9px;text-align:right;width:100%;padding-right:15mm;color:#888">${reportTitle}</div>`,
        footerTemplate: `<div style="font-size:9px;text-align:center;width:100%;color:#888">Page <span class="pageNumber"></span> of <span class="totalPages"></span> &middot; Generated by FinanceOS</div>`,
      });

      return Buffer.from(pdfBuffer);
    } finally {
      await browser.close();
    }
  },
};
