import { pgTable, uuid, text, numeric, date, timestamp, jsonb } from "drizzle-orm/pg-core";

/**
 * Business alerts generated by FinanceOS Core's Alerts Engine (Sprint 9) during
 * synchronization and stored in Neon. Read-only from the Dashboard — the
 * Dashboard NEVER calculates or writes alerts; it only reads this table.
 *
 * `entity_id` is null for portfolio-scoped alerts. `alert_type` is the
 * deterministic rule identifier (e.g. ar_overdue_critical, dso_elevated).
 * Numeric columns surface as strings via Drizzle — parse before use.
 */
export const alertsTable = pgTable("alerts", {
  id: uuid("id").primaryKey().defaultRandom(),
  entityId: uuid("entity_id"),
  alertType: text("alert_type").notNull(),
  severity: text("severity").notNull(),
  title: text("title").notNull(),
  message: text("message").notNull(),
  metricValue: numeric("metric_value"),
  threshold: numeric("threshold"),
  periodType: text("period_type"),
  periodStart: date("period_start"),
  status: text("status").notNull(),
  firstSeenAt: timestamp("first_seen_at", { withTimezone: true }).notNull(),
  lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).notNull(),
  resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  source: text("source").notNull(),
  metadata: jsonb("metadata"),
});

export type AlertRow = typeof alertsTable.$inferSelect;

// Aliases matching the naming used by the GitHub-authored api-server services:
// they import { alerts }.
export const alerts = alertsTable;
export type Alert = AlertRow;
